name: ai_shopping_assistant

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_shopping_assistant
    ports:
      - "8501:8501"  # Streamlit
      - "8001:8001"  # Widget
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Монтируем код для разработки (изменения применяются без пересборки)
      - ./back:/app/back
      - ./widget:/app/widget
      # Опционально: монтируем данные, если хотите обновлять их без пересборки
      - ./back/database:/app/back/database:ro
      - ./logs.db:/app/logs.db
    restart: unless-stopped
